name: Hello

on:
    push:
        branches:
        - master 
    pull_request:
      branches:
            - master
    workflow_dispatch:

jobs: 
    hello: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: hello world
              run: echo "Hello Shahed"
              shell: bash
    goodBye:
        runs-on: ubuntu-latest
        steps:
            - name: GoodBye
              run: echo "GoodBye"
              shell: bash
#Say Hello

